version: '2'

services:
    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes_from:
            - php
        volumes:
            - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./logs/nginx:/var/log/nginx
            - ./logs/symfony:/var/www/code/var/logs
        depends_on:
            - php

    php:
        build:
            context: ./config/php/
        volumes:
            - ${APP_PATH}:/var/www/code
            - ./config/php/php.ini:/usr/local/etc/php/php.ini:ro
        env_file:
            - .env
        expose:
            - 9000

    mysql:
        image: mysql:5.7.16
        volumes:
            - ./data/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}